/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/MFA.glb
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useCharacterAnimations } from "../contexts/CharacterAnimations";

const MFA = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/MFA.glb')
  const { actions, names } = useAnimations(animations, group)
  console.log(names)
  const { setAnimations, animationIndex } = useCharacterAnimations();

  useEffect(() => {
    setAnimations(names);
  }, [names]);

  useEffect(() => {
    actions[names[animationIndex]].reset().fadeIn(0.5).play();
    return () => {
      actions[names[animationIndex]].fadeOut(0.5);
    };
  }, [animationIndex]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Sunglasses_frames_Plane006" geometry={nodes.Sunglasses_frames_Plane006.geometry} material={nodes.Sunglasses_frames_Plane006.material} skeleton={nodes.Sunglasses_frames_Plane006.skeleton} />
        </group>
      </group>
    </group>
  )
}
export default MFA
useGLTF.preload('/models/MFA.glb')
