/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/scene.gltf
Author: ottobite (https://sketchfab.com/ottobite)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-hacked-pc-sketchfabweeklychallenge-192ab9d4706f4ffaaf22f9a299289d75
Title: Stylized Hacked PC #SketchfabWeeklyChallenge
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Scene =(props) =>{
  const { nodes, materials } = useGLTF('/models/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0-2,-2,-0.6]} scale={21.28} rotation={[0,0,90]}>
        <mesh geometry={nodes.Final_lambert1_0.geometry} material={materials.lambert1} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}
export default Scene
useGLTF.preload('/models/scene.gltf')
